const icons = {
  family: [
    { label: 'Mom', icon: '👩' },
    { label: 'Mom & Dad', icon: '👨‍👩' },
    { label: 'Dad', icon: '👨' },
    { label: 'Moms', icon: '👩👩' },
    { label: 'Dads', icon: '👨👨' },
    { label: 'Guardian', icon: '🦹' },
    { label: 'Other', icon: '💝' },
  ],
  ages: [
    { label: 'Expecting', icon: '🐣' },
    { label: 'Newborn', icon: '👶' },
    { label: 'Infant', icon: '🍼' },
    { label: 'Toddler', icon: '🧸' },
    { label: 'Pre Schooler', icon: '✏️' },
    { label: 'School Age', icon: '🛴' },
    { label: 'Teenager', icon: '👑' },
  ],
  pets: [
    { label: 'Cat', icon: '😺' },
    { label: 'Small Dog', icon: '🐕' },
    { label: 'Pig', icon: '🐷' },
    { label: 'Large Dog', icon: '🐕' },
    { label: 'Cow', icon: '🐮' },
    { label: 'Butterfly', icon: '🦋' },
    { label: 'Turtle', icon: '🐢' },
    { label: 'Snake', icon: '🐍' },
    { label: 'Parrot', icon: '🦜' },
    { label: 'Rabbit', icon: '🐰' },
    { label: 'Sheep', icon: '🐑' },
    { label: 'Duck', icon: '🦆' },
    { label: 'Horse', icon: '🐎' },
    { label: 'Frog', icon: '🐸' },
    { label: 'Gecko', icon: '🦎' },
    { label: 'Whale', icon: '🐳' },
    { label: 'Chicken', icon: '🐔' },
    { label: 'Hamster', icon: '🐹' },
    { label: 'Dinosaur', icon: '🦕' },
    { label: 'Baby Elephant', icon: '🐘' },
    { label: 'Unicorn', icon: '🦄' },
    { label: 'Other', icon: '🐾' },
    { label: 'None', icon: '⛔' },
  ],
  creative: [
    { label: 'Dance', icon: '💃' },
    { label: 'DIY', icon: '⭐' },
    { label: 'Painting', icon: '🎨' },
    { label: 'Drama', icon: '🎭' },
    { label: 'Gaming', icon: '🎮' },
    { label: 'Baking', icon: '👨‍🍳' },
    { label: 'Singing', icon: '🎤' },
    { label: 'Pottery', icon: '🏺' },
    { label: 'Reading', icon: '📚' },
    { label: 'Arts & Crafts', icon: '🎨' },
    { label: 'DJing', icon: '🎧' },
    { label: 'Magic', icon: '✨' },
    { label: 'Film Making', icon: '🎥' },
    { label: 'Cooking', icon: '🔍' },
    { label: 'Photography', icon: '📸' },
    { label: 'Videography', icon: '📹' },
    { label: 'Fashion Design', icon: '💎' },
    { label: 'Other', icon: '🎨' },
  ],
  instruments: [
    { label: 'Piano', icon: '🎹' },
    { label: 'Guitar', icon: '🎸' },
    { label: 'Accordion', icon: '🪗' },
    { label: 'Trumpet', icon: '🎺' },
    { label: 'Banjo', icon: '🪕' },
    { label: 'Drum', icon: '🥁' },
    { label: 'Maracas', icon: '🎵' },
    { label: 'Saxophone', icon: '🎷' },
    { label: 'Flute', icon: '🎼' },
    { label: 'Violin', icon: '🎻' },
    { label: 'Conga', icon: '🥁' },
    { label: 'Other', icon: '🎵' },
  ],
  sports: [
    { label: 'Ice skating', icon: '⛸️' },
    { label: 'Skiing', icon: '⛷️' },
    { label: 'Basketball', icon: '🏀' },
    { label: 'Hockey', icon: '🏑' },
    { label: 'Soccer', icon: '⚽' },
    { label: 'Rowing', icon: '🚣' },
    { label: 'Hiking', icon: '🥾' },
    { label: 'Wrestling', icon: '🤼' },
    { label: 'Football', icon: '🏈' },
    { label: 'Surfing', icon: '🏄' },
    { label: 'Chess', icon: '♟️' },
    { label: 'Volleyball', icon: '🏐' },
    { label: 'Tennis', icon: '🎾' },
    { label: 'Baseball', icon: '⚾' },
    { label: 'Karate', icon: '🥋' },
    { label: 'Track', icon: '🏃' },
    { label: 'Golf', icon: '⛳' },
    { label: 'Rugby', icon: '🏉' },
    { label: 'Polo', icon: '🏇' },
    { label: 'Cycling', icon: '🚴' },
    { label: 'Bowling', icon: '🎳' },
    { label: 'Badminton', icon: '🏸' },
    { label: 'Cricket', icon: '🏏' },
    { label: 'Gymnastics', icon: '🤸' },
    { label: 'Swimming', icon: '🏊' },
    { label: 'Water Polo', icon: '🤽' },
    { label: 'Roller skate', icon: '🛼' },
    { label: 'Skateboarding', icon: '🛹' },
    { label: 'Horseback Riding', icon: '🏇' },
    { label: 'Other', icon: '🎯' },
  ],
  stem: [
    { label: 'Coding', icon: '💻' },
    { label: 'Sciences', icon: '🧬' },
    { label: 'Robotics', icon: '🤖' },
    { label: 'Mathematics', icon: '📊' },
    { label: 'Other', icon: '🔬' },
  ],
  diet: [
    { label: 'Vegan', icon: '🥬' },
    { label: 'Vegetarian', icon: '🥗' },
    { label: 'Halal', icon: '🍖' },
    { label: 'Meat Eater', icon: '🍗' },
    { label: 'Kosher', icon: '🥩' },
    { label: 'Pescatarian', icon: '🐟' },
    { label: 'Sugar Free', icon: '🍬' },
    { label: 'None', icon: '⛔' },
    { label: 'Other', icon: '🥑' },
  ],
  rules: [
    { label: 'No Screens', icon: '📱' },
    { label: 'No Vapping', icon: '💨' },
    { label: 'Be Kind', icon: '😊' },
    { label: 'No Hitting', icon: '👊' },
    { label: 'No Nuts', icon: '🥜' },
    { label: 'No Swearing', icon: '🤬' },
    { label: 'No Long Nails', icon: '💅' },
    { label: 'No Bullying', icon: '🐂' },
    { label: 'No Perfume', icon: '🌸' },
    { label: 'No Smoking', icon: '😤' },
    { label: 'No Throwing Balls', icon: '🔴' },
    { label: 'No Jumping On Furniture', icon: '🛋️' },
    { label: 'Other', icon: '🎯' },
  ],
  religion: [
    { label: 'Islam', icon: '🕌' },
    { label: 'Taoism', icon: '☯️' },
    { label: 'Buddhism', icon: '🕉️' },
    { label: 'Judaism', icon: '✡️' },
    { label: 'Hinduism', icon: '🕉️' },
    { label: 'Christianity', icon: '✝️' },
    { label: 'Athesisim', icon: '🧬' },
    { label: 'Other', icon: '🙏' },
  ],
  foodAllergies: [
    { label: 'Milk', icon: '🥛' },
    { label: 'Eggs', icon: '🥚' },
    { label: 'Peanuts', icon: '🥜' },
    { label: 'Treenut', icon: '🌳' },
    { label: 'Fish', icon: '🐟' },
    { label: 'Shellfish', icon: '🦐' },
    { label: 'Soy', icon: '🫘' },
    { label: 'Wheat', icon: '🌾' },
    { label: 'Other', icon: '🍽️' },
  ],
  environmentalAllergies: [
    { label: 'Pollen', icon: '🌸' },
    { label: 'Dust mites', icon: '💨' },
    { label: 'Mold', icon: '🍄' },
    { label: 'Animal Dander', icon: '🐕' },
    { label: 'Insect sting', icon: '🐝' },
    { label: 'Other', icon: '🌲' },
  ],
  otherAllergies: [
    { label: 'Latex', icon: '🧤' },
    { label: 'Perfume', icon: '🌹' },
    { label: 'Cleaning Chemicals', icon: '💧' },
    { label: 'Metal', icon: '⚙️' },
    { label: 'Other', icon: '➕' },
  ],
  caregiverTypes: [
    { label: 'Night Nurse', icon: '🌙' },
    { label: 'Governess', icon: '👩' },
    { label: 'Babysitter', icon: '🧁' },
    { label: 'Nanny', icon: '👶' },
    { label: 'Manny', icon: '👑' },
    { label: 'Au Pair', icon: '🗽' },
    { label: 'Caregiver/Housekeeper', icon: '🥜' },
    { label: 'Caregiver/Personal Assistant', icon: '📅' },
    { label: 'Caregiver/Household Manager', icon: '🗣' },
  ],
};
